package com.golfhandicapcalculator.enterprise.service;

import com.golfhandicapcalculator.enterprise.dto.Player;
import com.golfhandicapcalculator.enterprise.dto.Score;

import java.util.List;
import java.io.IOException;

/**
 * Service interface for managing players and their scores in the golf handicap calculation system.
 * <p>
 * This interface defines the business logic and operations for handling player-related data, such as creating,
 * updating, and deleting players, as well as managing scores associated with players. It serves as an abstraction
 * between the controller layer and the underlying data access layer (e.g., DAOs).
 * </p>
 */
public interface IPlayerServices {

    /**
     * Retrieves all players in the system.
     * <p>
     * This method fetches a list of all players currently registered in the system.
     * </p>
     *
     * @return a list of {@link Player} objects representing all players.
     */
    List<Player> getAllPlayers();

    /**
     * Retrieves a specific player by their unique player ID.
     * <p>
     * This method fetches the player details for the given player ID.
     * </p>
     *
     * @param playerId the ID of the player to retrieve.
     * @return the {@link Player} object for the given ID, or {@code null} if not found.
     */
    Player getPlayerById(Long playerId);

    /**
     * Creates a new player in the system.
     * <p>
     * This method stores the provided player details and creates a new player in the system.
     * The player's unique ID is typically generated upon creation.
     * </p>
     *
     * @param player the {@link Player} object to create.
     * @return the created {@link Player} object, including any autogenerated fields such as the player ID.
     */
    Player createPlayer(Player player);

    /**
     * Updates an existing player's information.
     * <p>
     * This method updates the details of an existing player, identified by the provided player ID.
     * If the player with the specified ID is not found, the operation may return {@code null}.
     * </p>
     *
     * @param playerId the ID of the player to update.
     * @param player the {@link Player} object containing the updated information.
     * @return the updated {@link Player} object, or {@code null} if the player was not found.
     */
    Player updatePlayer(Long playerId, Player player);

    /**
     * Deletes a player from the system.
     * <p>
     * This method removes the player identified by the provided player ID from the system.
     * </p>
     *
     * @param playerId the ID of the player to delete.
     */
    void deletePlayer(Long playerId);

    /**
     * Retrieves all scores associated with a specific player.
     * <p>
     * This method fetches a list of scores that belong to the player with the specified player ID.
     * </p>
     *
     * @param playerId the ID of the player whose scores are to be retrieved.
     * @return a list of {@link Score} objects representing the scores for the specified player.
     */
    List<Score> getPlayerScores(Long playerId);

    /**
     * Adds a score to a player's record.
     * <p>
     * This method adds a new score to the player identified by the provided player ID.
     * If there is an issue with adding the score (e.g., invalid data), an {@link IOException} is thrown.
     * </p>
     *
     * @param playerId the ID of the player to whom the score should be added.
     * @param score the {@link Score} object containing the score to add.
     * @return the newly added {@link Score} object.
     * @throws IOException if there is an error while saving the score.
     */
    Score addScoreToPlayer(Long playerId, Score score) throws IOException;

    /**
     * Updates an existing score for a player.
     * <p>
     * This method updates the score identified by the provided score ID for the player with the given player ID.
     * If the score or player is not found, an {@link IOException} may be thrown.
     * </p>
     *
     * @param playerId the ID of the player whose score should be updated.
     * @param scoreId the ID of the score to update.
     * @param score the {@link Score} object containing the updated score details.
     * @return the updated {@link Score} object.
     * @throws IOException if there is an error while updating the score.
     */
    Score updatePlayerScore(Long playerId, Long scoreId, Score score) throws IOException;
}
